[package]
name = "vocab"
version = "0.1.0"
authors = ["Michał Jastrzębski <inc0@github.com>"]
edition = "2018"

[lib]
name = "vocab"
crate-type = ["cdylib"]

[dependencies.pyo3]
version = "0.6.0"
features = ["extension-module"]
